#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of Polymorphine/Dev package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * PHP_CodeSniffer detects violations of a defined coding standard.
 *
 * @author    Greg Sherwood <gsherwood@squiz.net>
 * @copyright 2006-2015 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license   https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/HEAD/licence.txt BSD Licence
 */

// Checks for $argv[1] are workarounds for PhpStorm inspection that either sends file content
// through STDIN ($argv[1] = '-') or checks for version number ($argv[1] = '--version')
$commandType = $argv[1] ?? null;
$codeSniffer = new PhpCSScript();

switch ($commandType) {
    case '--version':
        $exitCode = $codeSniffer->versionCheck($argv);
        break;
    case '-':
        $exitCode = $codeSniffer->fileInspection($argv);
        break;
    default:
        $exitCode = $commandType ? $codeSniffer->fileCheck($argv) : $codeSniffer->projectScan();
        if (!$exitCode) {
            echo '--- Done (OK) ---';
        }
}

exit($exitCode);


class PhpCSScript
{
    private PHP_CodeSniffer\Runner $runner;
    private bool                   $selfCheck;

    public function __construct()
    {
        $scriptRoot = getcwd() === __DIR__ ? __DIR__ : dirname(__DIR__, 3);
        require_once $this->path($scriptRoot, 'vendor/squizlabs/php_codesniffer/autoload.php');

        $this->runner    = new PHP_CodeSniffer\Runner();
        $this->selfCheck = $scriptRoot === __DIR__;
    }

    public function projectScan(): int
    {
        $standard = $this->path(__DIR__, $this->selfCheck ? 'phpcs.xml.dist' : 'phpcs.xml');
        $args     = ['--extensions=php', '--standard=' . $standard, '--colors', '--ignore=*/code-samples/*'];
        $this->selfCheck || $this->includeProjectAutoload(getcwd());
        return $this->runScript(['--version']) | $this->runScript([...$args, 'src', 'tests']);
    }

    public function versionCheck(array $args): int
    {
        return $this->runScript($args);
    }

    public function fileInspection(array $args): int
    {
        // PhpStorm provides project root as working directory as a CLI option path to standard ruleset
        $cwd      = explode('=', $args[2])[1];
        $standard = $this->path(__DIR__, $cwd === __DIR__ ? 'phpcs.xml.dist' : 'phpcs.xml');
        $args[2]  = '--standard=' . $standard;
        $this->includeProjectAutoload($cwd);
        return $this->runScript($args);
    }

    public function fileCheck(array $args): int
    {
        $cwd      = getcwd();
        $standard = $this->path(__DIR__, $this->selfCheck ? 'phpcs.xml.dist' : 'phpcs.xml');
        $args     = ['--extensions=php', '--standard=' . $standard, '--colors', '--ignore=*/code-samples/*', $args[1]];
        $this->includeProjectAutoload($cwd);
        return $this->runScript($args);
    }

    private function runScript(array $args): int
    {
        $_SERVER['argv'] = [__FILE__, ...$args];
        return $this->runner->runPHPCS();
    }

    private function includeProjectAutoload(string $projectRoot): void
    {
        require_once $this->path($projectRoot, 'vendor/autoload.php');
    }

    private function path(string $root, string $path): string
    {
        return $root . DIRECTORY_SEPARATOR . str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $path);
    }
}
