#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of Polymorphine/Dev package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Shudd3r\Skeletons\Application;
use Shudd3r\Skeletons\InputArgs;
use Shudd3r\Skeletons\Environment\Files\Directory\LocalDirectory;
use Shudd3r\Skeletons\Replacements\Replacement;
use Shudd3r\Skeletons\Replacements\Source;
use Shudd3r\Skeletons\Templates\Contents;
use Shudd3r\Skeletons\Templates\Template;

// This script should be executed from package root directory
$projectDirectory = getcwd();
if (!file_exists($projectDirectory . '/composer.json')) {
    fwrite(STDERR, <<<'MSG'
        Cannot find `composer.json` in current directory.
        Run the script from project's root directory.
        MSG);
    exit(1);
}

$scriptRoot = $projectDirectory === __DIR__ ? __DIR__ : dirname(__DIR__, 3);
if (!file_exists($scriptRoot . '/vendor/autoload.php')) {
    fwrite(STDERR, <<<'MSG'
        Cannot find `vendor/autoload.php` in script's root directory.
        Make sure you installed it with Composer.
        MSG);
    exit(1);
}

require_once $scriptRoot . '/vendor/autoload.php';

$args = new InputArgs($argv ?? []);

$skeleton = new LocalDirectory(__DIR__ . '/template');
$package  = new LocalDirectory($projectDirectory);
$app      = new Application($package, $skeleton);

$app->backup(new LocalDirectory($projectDirectory . '/.dev/.skeleton-backup'));

$app->replacement('package.name')->add(new Replacement\PackageName());
$app->replacement('repository.name')->add(new Replacement\RepositoryName('package.name'));
$app->replacement('package.description')->add(new Replacement\PackageDescription('package.name'));
$app->replacement('namespace.src')->add(new Replacement\SrcNamespace('package.name'));
$app->replacement('author.name')
    ->build(fn (Source $source) => $source->composer()->value('authors.0.name') ?? 'Author Name')
    ->argumentName('author')
    ->inputPrompt('Author\'s name')
    ->description('Name of package author [format: non-empty string]' . PHP_EOL . 'Replaces {%s} placeholder')
    ->validate(fn (string $value) => !empty($value));
$app->replacement('author.email')
    ->build(fn (Source $source) => $source->composer()->value('authors.0.email') ?? 'default@example.com')
    ->argumentName('email')
    ->inputPrompt('Author\'s email address')
    ->description('Email address of package author [format: <username>@<domain>]' . PHP_EOL . 'Replaces {%s} placeholder')
    ->validate(fn (string $value) => $value === filter_var($value, FILTER_VALIDATE_EMAIL));

$isUpdate = $args->command() === 'update';
$isSelf   = $projectDirectory === __DIR__;

$app->template('composer.json')->createWith(function (Contents $contents) use ($isSelf, $isUpdate) {
    $placeholders = ['{$tpl.REQUIRE_DEV}', '{$tpl.PHP_EXEC}', '{$tpl.PHPCS}'];
    $replacements = $isSelf
        ? ['null', '@php ', 'phpcs.xml.dist']
        : ['{ "polymorphine/dev": null }', '', 'vendor/polymorphine/dev/phpcs.xml'];
    $baseTemplate = new Template\BasicTemplate(str_replace($placeholders, $replacements, $contents->template()));
    return new Template\MergedJsonTemplate($baseTemplate, $contents->package(), $isUpdate);
});

$app->template('.github/workflows/build.yml')->createWith(function (Contents $contents) use ($isSelf) {
    $placeholders = ['${tpl.PHP_EXEC}', '${tpl.PHPCS}'];
    $replacements = $isSelf
        ? ['php ', 'phpcs.xml.dist']
        : ['vendor/bin/', 'vendor/polymorphine/dev/phpcs.xml'];
    return new Template\BasicTemplate(str_replace($placeholders, $replacements, $contents->template()));
});

$app->template('LICENSE')->createWith(function (Contents $contents) {
    return new Template\BasicTemplate(str_replace('{$tpl.CURRENT_YEAR}', date('Y'), $contents->template()));
});

$exitCode = $app->run($args);
exit($exitCode);
