#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of Polymorphine/Dev package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$argv or exit('CLI script executable');

error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);
set_error_handler(static function (int $severity, string $message, string $file, int $line): bool {
    if ($severity & error_reporting()) {
        throw new ErrorException($message, 0, $severity, $file, $line);
    }
    return true;
});

if (PHP_VERSION_ID === 80000) {
    fwrite(STDERR, 'PHP CS Fixer is not able run on PHP 8.0.0 due to bug in PHP tokenizer');
    exit(1);
}

require_once (getcwd() === __DIR__ ? __DIR__ : dirname(__DIR__, 3)) . '/vendor/autoload.php';

// Restart if xdebug is loaded, unless the environment variable PHP_CS_FIXER_ALLOW_XDEBUG is set.
(new Composer\XdebugHandler\XdebugHandler('PHP_CS_FIXER'))->check();

$fixer = new CSFixerScript();
switch ($argv[1] ?? '') {
    case '--version':
    case 'list-sets':
        $exitCode = $fixer->runScript($argv);
        break;
    case 'fix':
        $exitCode = $fixer->fileInspection($argv);
        break;
    case '--fix':
        $exitCode = $fixer->fixFiles($argv);
        break;
    default:
        $exitCode = $fixer->checkFiles($argv);
}

exit($exitCode);


class CSFixerScript
{
    private const CONFIG   = '--config=' . __DIR__ . DIRECTORY_SEPARATOR . 'cs-fixer.php';
    private const CLI_ARGS = [self::CONFIG, '--path-mode=intersection', '--show-progress=none', 'fix'];

    public function fileInspection(array $args): int
    {
        $args[2] = str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $args[2]);
        $args[3] = self::CONFIG;
        Polymorphine\Dev\FixerSetup::usingTempPath($args[2]);
        return $this->runScript([...$args, '--path-mode=intersection']);
    }

    public function checkFiles(array $args): int
    {
        // Check either single file or entire project
        $files = count($args) > 1 ? [$args[1]] : ['src', 'tests'];
        return $this->runScript([$args[0], '--dry-run', '-v', ...self::CLI_ARGS, ...$files]);
    }

    public function fixFiles(array $args): int
    {
        // Fix either single file or entire project
        $files = count($args) > 2 ? [$args[2]] : ['src', 'tests'];
        return $this->runScript([$args[0], ...self::CLI_ARGS, ...$files]);
    }

    public function runScript(array $args): int
    {
        $_SERVER['argv'] = $args;
        $fixer = new PhpCsFixer\Console\Application();
        $fixer->setAutoExit(false);
        return $fixer->run();
    }
}
